### PR TITLE
Remove jackOptions for compatibility with the latest Android

### PR DESCRIPTION
**Pull request by ccorcos**
Fixes https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/issues/107

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
🤞fingers crossed this doesn't break older versions. Thx!

**Comment by ccorcos** [comment]
It might, but then then should either upgrade or use an older version. :)

**Comment by garyjohnson** [comment]
Is there going to be a new version released with this fix? Looks like I'll be forced to upgrade cordova-android due to this issue https://github.com/apache/cordova-android/pull/450 and this plugin appears to not be compatible without this PR.

**Comment by EddyVerbruggen** [comment]
Done.

**Pull request merged**
