### PR TITLE
iOS 10 updates

### PR DESCRIPTION
**Pull request by johnthepink**
This brings support for two new methods in iOS 10 for `SFSafariViewController`:

1. [`preferredBarTintColor`](https://developer.apple.com/reference/safariservices/sfsafariviewcontroller/2274394-preferredbartintcolor) - allows you to change the top and bottom bar background color
2. [`preferredControlTintColor`](https://developer.apple.com/reference/safariservices/sfsafariviewcontroller/2274393-preferredcontroltintcolor) - replaces using `tintColor` directly on the view

Now, you can do something like this:

I added some compiler directives, so this should be backwards compatible. 

Let me know if you have any thoughts!

### CODE REVIEW

**Comment by johnthepink** [comment]
I'm thinking we will probably need to add a fallback for people wanting to change the bar color. In the example above (blue bar with white text), iOS 10 would look like the picture, and iOS 9 would have a white bar with white text, which is not ideal. 

So, maybe we add a "fallbackTint" option that allows you to handle that case? I'll update the PR if you agree.

**Comment by EddyVerbruggen** [comment]
Looks good, John! I'll merge this and tweak it a bit as I found an issue where we not only need a compile time check for iOS 10 but also a runtime check.

Regarding the fallback: good point. I'll make sure `tintColor` will work as it does now. If you only pass in `tintColor` and not `controlTintColor` both iOS 9 and 10 will behave the same.

If you pass in `controlTintColor` without `tintColor` then on iOS 9 it will use `controlTintColor` but can be overridden with `tintColor` as before.

**Comment by EddyVerbruggen** [comment]
@johnthepink please review my latest changes

**Comment by johnthepink** [comment]
@EddyVerbruggen I dig it. Thanks so much!

**Pull request merged**
