### PR TITLE
Add ability to show action items

### PR DESCRIPTION
**Pull request by mausibris**
Hello,

I would like to show an action item.
In the PR is the code that belongs into the library. Im app there must be code like this:

```
- (NSArray<UIActivity *> *)safariViewController:(SFSafariViewController *) controller
                            activityItemsForURL:(NSURL *)URL
                                          title:(nullable NSString *)title {
    MyActivity* activity = MyActivity.new;
    return @[activity];
}

@implementation MyActivity

- (NSString *)activityType {
...
}

- (NSString *)activityTitle {
...
}
...
@end

```

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi! Thanks for sharing this - can you please elaborate on how a developer could use this feature?

**Comment by mausibris** [comment]
Hi. Sorry for the long delay. I didn’t find a demo project to integrate it into... Basically you can use it as following:

In the main view controller header: add the ActivityItemProvider protocol
```
@interface MainViewController : CDVViewController<ActivityItemProvider>
@end
```

In the source file set the delegate and add the method to create the activity:
```
@implementation MainViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.

    SafariViewController* safariViewController = [self getCommandInstance:@"SafariViewController"];
    safariViewController.activityItemProvider = self;
}

- (NSArray<UIActivity *> *)safariViewController:(SFSafariViewController *) controller activityItemsForURL:(NSURL *)URL title:(nullable NSString *)title {
    MyActivity* activity = MyActivity.new;
    activity.mainController = self;
    return @[activity];
}

@end
```

Now create the activity class you want to use. This must be an UIActivity. Header:
```
@interface MyActivity : UIActivity
@property (nonatomic) MainViewController* mainController; //optional...
@end
```
Source:
```
@implementation MyActivity

- (NSString *)activityType
{
    return @"myappid.share";
}

- (NSString *)activityTitle
{
    return @„text to show
![photo_2016-10-18_17-14-33](https://cloud.githubusercontent.com/assets/7298549/19484000/654a8790-9556-11e6-97b3-acccc88f9d63.jpg)
“;
}

- (UIImage *)activityImage
{
    UIImage* img = [UIImage imageNamed:@"icon-with-alpha“];
    return omg;
}

- (BOOL)canPerformWithActivityItems:(NSArray *)activityItems
{
    return YES;
}

- (void)prepareWithActivityItems:(NSArray *)activityItems
{
}

- (UIViewController *)activityViewController
{
    return nil;
}

- (void)performActivity
{
    // This is where you can do anything you want, and is the whole reason for creating a custom
    // UIActivity

    [self activityDidFinish:YES];
}

@end
```

Now it looks like:
![photo_2016-10-18_17-14-33]

**Comment by mausibris** [comment]
Hi! Just bringing this again to your attention ;). Is the description easy to understand?

**Comment by EddyVerbruggen** [comment]
Sorry, I missed this one.

Merged! 👍 🎉

**Pull request merged**
